image: docker.cbp.dhs.gov/cloud/openjdk-build:11

include: 
    - https://gitlab.cbp.dhs.gov/artifacts/templates/raw/master/sast-gitlab-ci.yml

variables:
  MAVEN_REPO_PATH: "$CI_PROJECT_DIR/.m2/repository"
  SECURE_ANALYZERS_PREFIX: "docker.cbp.dhs.gov/gitlab/analyzers"
  SAST_ANALYZER_IMAGE_PREFIX: "$SECURE_ANALYZERS_PREFIX"
  SAST_DEFAULT_ANALYZERS: "spotbugs, secrets"
  SAST_ANALYZER_IMAGE_TAG: 2
  SCAN_KUBERNETES_MANIFESTS: "false"
  SAST_GOSEC_LEVEL: 2 #|0| Ignore gosec vulnerabilities under given confidence level. Integer, 0=Undefined, 1=Low, 2=Medium, 3=High.
  DS_EXCLUDED_PATHS: bin, dist, spec, test, tests, tmp
  SAST_BANDIT_EXCLUDED_PATHS: '*/bin/*,*/dist/*,*/static/*,*/target/site/*,*/target/site/jacoco/*,*/target/site/jacoco/resources/*'
  SAST_EXCLUDED_PATHS: bin, dist, spec, test, tests, tmp, jacoco

cache:
  key: "${CI_COMMIT_REF_NAME}"
  untracked: true
  paths:
  - .m2/
  - ctpat-pui/target/
  policy: pull-push

stages:
    - build
    - sast
    - publish

setup:
  stage: .pre
  script:
  - |
   mkdir -p ${MAVEN_REPO_PATH}
   echo "<settings><localRepository>${MAVEN_REPO_PATH}</localRepository></settings>">$CI_PROJECT_DIR/.m2/settings.xml
  artifacts:
    paths:
     - .m2/

build:
  stage: build    
  script:
    - "mvn -f ctpat-pui/pom.xml clean verify"
  after_script:
    - cat ctpat-pui/target/site/jacoco-ut/index.html
  coverage: /Total.*?([0-9]{1,3})%/

  artifacts:
    paths:
      - ctpat-pui/target/classes/
      - ctpat-pui/target/surefire-reports/TEST-*.xml
      - ctpat-pui/target/site/jacoco-ut/
      - .m2/
    expire_in: 1 hrs
    reports: 
      junit: ctpat-pui/target/surefire-reports/TEST-*.xml
     
spotbugs-sast:
  dependencies:
    - build
  variables:
    COMPILE: "false"
  artifacts:
    reports:
      sast: gl-sast-report.json
  before_script:
    - ls -al

pages:
    stage: publish
    allow_failure: true
    dependencies:
        - build
    script:
    - ls -al ctpat-pui/target/site/jacoco-ut/
    - mv ctpat-pui/target/site/jacoco-ut/public/   
    - ls -al public/
    artifacts:
      paths:
        - public

